import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>EventBud</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col">
        <header className="flex flex-col items-center justify-center flex-1">
          <h1 className="text-6xl font-bold">EventBud</h1>
          <p className="mt-3 text-2xl">
            Find the best events in your city, all in one place.
          </p>
          <div className="mt-5">
          <Link href="/main" legacyBehavior>
            <a className="px-4 py-2 text-lg font-semibold text-white bg-blue-600 rounded-md hover:bg-blue-700">
              View Events
            </a>
          </Link>
          </div>
        </header>

      </main>
    </>
  );
}
