import React from "react";
import Head from "next/head";

export const login = () => {

    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="max-h-screen">
                <div className='flex flex-row max-h-screen'>
                    <div className="w-1/2 h-full">
                        <img src="/public/images/loginnsignup/1.png" alt="vdo"></img>
                    </div>
                    <div className="flex flex-col justify-center items-center h-full w-1/2">
                        <div>
                            <h1 className="font-montserrat text-2xl font-bold text-center">Log in</h1>
                            <p className="font-montserrat">Email</p>
                            <span className="text-red-600">*</span>
                            <div className="flex flex-col">
                                <form className="flex">
                                    <input className="border-2 border-gray-300 rounded-md px-2 py-1" type="text" placeholder="Email"></input>
                                </form>
                            </div>
                        </div>  
                    </div>
                </div>
            </main>
        </>
    )
}

export default login